const $=id=>document.getElementById(id);
let token=new URLSearchParams(location.hash.slice(1)).get('token')||sessionStorage.getItem('vod-token')||'';
sessionStorage.setItem('vod-token',token);history.replaceState(null,'',location.pathname);
let info=null, state={}, rendered='', lastDetection='', busy=false, speechReady=false, loadedProject='', researchRendered='', localError='';
async function api(action,data){const response=await fetch('/api/'+action,{method:data===undefined?'GET':'POST',headers:{'Content-Type':'application/json','X-Vod-Token':token},body:data===undefined?undefined:JSON.stringify(data)});const result=await response.json();if(!response.ok)throw Error(result.error||'Erreur de communication');return result;}
function error(e){localError=e.message||String(e);$('error').textContent=localError;$('error').hidden=false;}
function protect(fn){return async()=>{try{await fn()}catch(e){error(e)}}}
function time(n){n=Math.floor(n);return [Math.floor(n/3600),Math.floor(n/60)%60,n%60].map(v=>String(v).padStart(2,'0')).join(':')}
function startSeconds(){return $('start').value.split(':').reduce((a,v)=>a*60+Number(v),0)}
function estimate(){if(!info)return;const remain=info.duration-startSeconds(), duration=Number($('minutes').value)*60;if(remain<=0||duration<=0){$('estimate').textContent='Le début doit précéder la fin de la VOD.';return}let count=Math.max(1,Math.ceil((remain-.1)/duration));if(count>1&&remain-duration*(count-1)<duration-.1)count--;$('estimate').textContent=`${count} épisode${count>1?'s':''} estimé${count>1?'s':''} · ${time(remain)} de contenu · dernier : ${time(remain-duration*(count-1))}`;}
async function inspect(){if(!$('source').value.trim())return;info=await api('probe',{source:$('source').value.trim().replace(/^"|"$/g,'')});$('source-info').textContent=`${time(info.duration)} · ${info.width} × ${info.height} · ${info.video.toUpperCase()}${info.audio?'':' · sans audio'}`;estimate();}
$('browse').onclick=protect(async()=>{const r=await pickPath('video',$('source').value);if(r.path){$('source').value=r.path;await inspect()}});
$('folder').onclick=protect(async()=>{const r=await pickPath('folder',$('output').value);if(r.path)$('output').value=r.path});
$('source').onchange=protect(inspect);$('start').oninput=estimate;$('minutes').oninput=estimate;
function config(){return {source:$('source').value.trim().replace(/^"|"$/g,''),start:$('start').value,minutes:$('minutes').value,output:$('output').value.trim().replace(/^"|"$/g,''),ai:$('ai').checked,provider:$('provider').value,openai_model:openaiModel(),api_key:$('provider').value==='openai'?$('api-key').value.trim():'',game:$('game').value.trim(),web:$('web').checked,first_episode:$('first-episode').value,project:loadedProject,reuse_transcript:$('reuse-transcript').checked}}
$('launch').onclick=protect(async()=>{localError='';await api('start',config());await poll()});
$('detect').onclick=protect(async()=>{await api('detect',config());await poll()});
$('install').onclick=protect(async()=>{await api('install',{});await poll()});
$('cancel').onclick=protect(async()=>{await api('cancel',{});$('cancel').disabled=true});
$('open').onclick=protect(()=>api('open',{}));
async function status(){try{const s=await api('status');speechReady=s.speech;const ready=$('provider').value==='openai'?s.speech&&s.editor:s.ready;$('ai-status').textContent=ready?'Les modèles locaux sont prêts':s.speech?'Whisper prêt · Qwen / modèles locaux à préparer':'Modèles locaux à préparer';$('ai-dot').classList.toggle('ready',ready);$('install').textContent=ready?'Vérifier l’IA':'Préparer l’IA';$('detect').disabled=busy||!s.speech;}catch(e){error(e)}}
function imageURL(path){return '/image?path='+encodeURIComponent(path)+'&token='+encodeURIComponent(token)+'&v='+Date.now()}
function el(tag,text,cls){const x=document.createElement(tag);if(text)x.textContent=text;if(cls)x.className=cls;return x}
function results(clips){const signature=JSON.stringify(clips);if(signature===rendered)return;rendered=signature;$('results').replaceChildren();$('results-section').hidden=!clips.length;clips.forEach((c,index)=>{const card=el('article',null,'clip');if(c.thumbnail){const img=el('img');img.src=imageURL(c.thumbnail);img.alt='Miniature de l’épisode '+c.number;card.append(img)}card.append(el('h3',`Épisode ${String(c.number).padStart(2,'0')} · ${time(c.duration)}`),el('p',c.status==='pending'?'Vidéo prête · analyse en attente':c.status==='analysing'?'Vidéo prête · analyse en cours':c.ai?'Titres proposés · clique pour copier':'Titre générique · sans analyse IA'));const list=el('ol');for(const title of c.titles){const li=el('li',title);li.tabIndex=0;const copy=protect(async()=>{await navigator.clipboard.writeText(title);li.textContent='Copié ✓';setTimeout(()=>li.textContent=title,1200)});li.onclick=copy;li.onkeydown=e=>{if(e.key==='Enter')copy()};list.append(li)}card.append(list);if(c.timings?.total)card.append(el('p',`Préparation : ${c.timings.total.toFixed(1)} s`,'caption'));if(c.summary)card.append(el('p',c.summary));if(c.timeline_summary?.length){const notes=el('details');notes.append(el('summary','Résumés par période de 5 minutes'));for(const block of c.timeline_summary){notes.append(el('h4',`${time(block.start)} → ${time(block.end)}`),el('p',block.summary));for(const event of block.events||[])notes.append(el('p','• '+event.event+(event.uncertainty?' · Incertain : '+event.uncertainty:'')));}if(c.summary_metrics)notes.append(el('p',`${c.summary_metrics.summary_characters} caractères de résumé / ${c.summary_metrics.raw_characters} caractères détaillés · résumé local sans coût API`,'caption'));card.append(notes);}if(c.warning)card.append(el('p',c.warning));if(c.thumbnail){const details=el('details');details.append(el('summary','Modifier la miniature'));const frames=el('div',null,'frames');let selected=c.frame;for(let i=1;i<=8;i++){const b=el('button');b.classList.toggle('selected',selected===i);b.title='Image '+i;const im=el('img');im.src=imageURL(c.directory+'/image_'+String(i).padStart(2,'0')+'.jpg');im.alt='Image '+i;b.append(im);b.onclick=()=>{selected=i;[...frames.children].forEach((ch,j)=>ch.classList.toggle('selected',j===i-1))};frames.append(b)}const input=el('input');input.value=c.thumbnail_text;input.maxLength=90;input.setAttribute('aria-label','Texte de la miniature');const save=el('button','Enregistrer la miniature','secondary');save.onclick=protect(async()=>{save.disabled=true;try{await api('thumbnail',{index,frame:selected,text:input.value});rendered='';await poll()}finally{save.disabled=false}});details.append(frames,input,save);card.append(details)}$('results').append(card)});}
async function poll(){try{const wasBusy=busy;state=await api('state');busy=state.busy;for(const id of ['launch','install','browse','folder','source','start','minutes','output','ai','game','web','first-episode','load-project','regenerate','reuse-transcript','provider','api-key','check-openai','openai-model','custom-model'])$(id).disabled=busy;$('detect').disabled=busy||!speechReady;$('cancel').hidden=!busy;if(!busy)$('cancel').disabled=false;$('stage').textContent=state.stage;$('progress').value=state.progress;$('logs').textContent=state.logs.join('\n')||'Ton prochain épisode commence ici.';$('logs').scrollTop=$('logs').scrollHeight;$('open').hidden=!state.output;$('error').hidden=!(state.error||localError);$('error').textContent=state.error||localError;results(state.clips);renderResearch(state.game_context);if(state.project){loadedProject=state.project;$('regenerate').hidden=false;$('reuse-row').hidden=false;}if(state.detected&&JSON.stringify(state.detected)!==lastDetection){lastDetection=JSON.stringify(state.detected);const d=$('detected');d.hidden=false;d.replaceChildren(el('div',`Paroles repérées à ${time(state.detected.start)} : « ${state.detected.text} »`),el('div','Vérifie ce passage : une musique chantée peut être confondue avec la voix du streamer.'));const b=el('button','Utiliser ce début','secondary');b.onclick=()=>{$('start').value=time(state.detected.start);estimate();d.hidden=true};d.append(b)}if((state.version||0)<8){$('launch').disabled=true;$('regenerate').disabled=true;error(new Error('Une mise à jour est en cours. Relance VOD Atelier pour charger la nouvelle analyse.'));}if(wasBusy&&!busy)await status();}catch(e){error(e)}}
function titleFormat(){const game=$('game').value.trim()||'Nom du jeu';$('title-format').textContent=`Une accroche intrigante [${game} #${$('first-episode').value||1}]`;localStorage.setItem('vod-game',$('game').value);}
$('game').value=localStorage.getItem('vod-game')||'';$('game').oninput=titleFormat;$('first-episode').oninput=titleFormat;titleFormat();
$('load-project').onclick=protect(async()=>{const picked=await pickPath('project',loadedProject);if(!picked.path)return;const result=await api('load_project',{project:picked.path});loadedProject=result.project;if(result.game)$('game').value=result.game;$('first-episode').value=result.first_episode;titleFormat();$('project-info').textContent=`${result.clips} clips chargés. Les vidéos seront conservées.`;$('reuse-row').hidden=false;$('regenerate').hidden=false;localError='';await poll();});
$('regenerate').onclick=protect(async()=>{localError='';await api('regenerate',{...config(),ai:true});await poll();});
function renderResearch(context){const signature=JSON.stringify(context);if(signature===researchRendered)return;researchRendered=signature;context=context||{};$('research-results').hidden=!(context.sources?.length||context.warning);$('research-overview').textContent=context.overview||'';$('research-warning').textContent=context.warning||'';const links=$('research-links');links.replaceChildren();for(const source of context.sources||[]){if(!/^https?:\/\//i.test(source.url))continue;const a=el('a',source.title+(source.read?' · page lue':' · aperçu du moteur'));a.href=source.url;a.target='_blank';a.rel='noopener noreferrer';links.append(a);}}
poll();status();setInterval(poll,1500);

function providerChanged(){const online=$('provider').value==='openai';$('openai-options').hidden=!online;$('local-options').hidden=false;$('local-help').hidden=false;$('local-models').textContent=online?'Whisper pour les paroles · Qwen pour les résumés de cinq minutes':'Whisper pour les paroles · Qwen pour les résumés et titres · Gemma 3 pour les images';localStorage.setItem('vod-provider',$('provider').value);}
$('provider').value=localStorage.getItem('vod-provider')==='openai'?'openai':'local';$('provider').onchange=providerChanged;providerChanged();
$('api-key').oninput=()=>{$('key-status').textContent='';};
$('check-openai').onclick=protect(async()=>{$('check-openai').disabled=true;$('key-status').textContent='Vérification…';try{const r=await api('check_openai',{api_key:$('api-key').value.trim(),openai_model:openaiModel()});$('key-status').textContent=r.message;}catch(e){$('key-status').textContent=e.message;}finally{$('check-openai').disabled=busy;}});

let pickerMode='video', pickerDirectory='', pickerParent='', pickerSelection='', pickerResolve=null, pickerBusy=false;
async function pickerNavigate(path){if(pickerBusy)return;pickerBusy=true;$('picker-error').hidden=true;$('picker-entries').textContent='Chargement…';$('picker-select').disabled=true;try{const data=await api('browse',{path,mode:pickerMode});pickerDirectory=data.path;pickerParent=data.parent;pickerSelection='';$('picker-path').value=data.path;$('picker-up').disabled=data.parent===data.path;$('picker-selected').textContent=pickerMode==='folder'?data.path:'Aucun fichier sélectionné';$('picker-select').disabled=pickerMode!=='folder';$('picker-roots').replaceChildren();for(const root of data.roots){const b=el('button',root,'text-button');b.onclick=()=>pickerNavigate(root);$('picker-roots').append(b);}$('picker-entries').replaceChildren();for(const entry of data.entries){const b=el('button',(entry.directory?'▸  ':'▧  ')+entry.name,'picker-entry');b.onclick=()=>{if(entry.directory){pickerNavigate(entry.path);return;}pickerSelection=entry.path;$('picker-selected').textContent=entry.name;$('picker-select').disabled=false;for(const sibling of $('picker-entries').children)sibling.classList.toggle('selected',sibling===b);};b.ondblclick=()=>{if(!entry.directory){pickerSelection=entry.path;pickerFinish();}};$('picker-entries').append(b);}if(!data.entries.length)$('picker-entries').append(el('p',pickerMode==='project'?'Aucun projet.json ici. Ouvre le dossier d’un projet.':pickerMode==='video'?'Aucune vidéo ici. Ouvre un autre dossier.':'Ce dossier est vide.','hint'));}catch(e){$('picker-entries').replaceChildren();$('picker-error').textContent=e.message;$('picker-error').hidden=false;}finally{pickerBusy=false;}}
function pickerFinish(){const path=pickerMode==='folder'?pickerDirectory:pickerSelection;if(!path)return;$('file-picker').close();pickerResolve?.({path});pickerResolve=null;}
function pickPath(mode,initial){if(window.pywebview?.api?.choose_path)return window.pywebview.api.choose_path(mode,initial||'').then(path=>({path:path||''}));pickerMode=mode;pickerSelection='';pickerDirectory='';$('picker-title').textContent=mode==='folder'?'Choisir le dossier des clips':mode==='project'?'Ouvrir un projet existant':'Choisir une vidéo';$('picker-hint').textContent=mode==='folder'?'Navigue jusqu’au dossier souhaité, puis clique sur Choisir.':'Ouvre les dossiers avec un clic, sélectionne le fichier puis clique sur Choisir.';$('file-picker').showModal();const promise=new Promise(resolve=>pickerResolve=resolve);pickerNavigate(initial||'');return promise;}
$('picker-up').onclick=()=>pickerNavigate(pickerParent);$('picker-navigation').onsubmit=e=>{e.preventDefault();pickerNavigate($('picker-path').value);};$('picker-select').onclick=pickerFinish;$('picker-close').onclick=()=>$('file-picker').close();$('file-picker').onclose=()=>{pickerResolve?.({path:''});pickerResolve=null;};

let modelCatalog=[];
function openaiModel(){return $('openai-model').value==='custom'?$('custom-model').value.trim():$('openai-model').value;}
function modelChanged(){const custom=$('openai-model').value==='custom';$('custom-model-row').hidden=!custom;const id=openaiModel(), model=modelCatalog.find(m=>m.id===id);$('key-status').textContent='';localStorage.setItem('vod-openai-model',id);const cost=$('model-cost');cost.replaceChildren();if(model){cost.append(document.createTextNode(`${model.hint} Tarifs indicatifs : ${model.input.toFixed(2)} $ / million de tokens d’entrée et ${model.output.toFixed(2)} $ / million de tokens de sortie, hors réduction du cache. Vérifiés le 30/09/2026. `));const link=el('a','Tarifs officiels de ce modèle');link.href='https://developers.openai.com/api/docs/models/'+encodeURIComponent(id);link.target='_blank';link.rel='noopener noreferrer';cost.append(link);}else{cost.textContent='Tarif non renseigné pour cet identifiant. Vérifie son prix et sa compatibilité dans la documentation OpenAI.';}}
async function loadModels(){try{const data=await api('models');modelCatalog=data.models;const remembered=localStorage.getItem('vod-openai-model')||data.default;$('openai-model').replaceChildren();for(const model of modelCatalog){const option=el('option',`${model.id} · ${model.input.toFixed(2)} $ entrée / ${model.output.toFixed(2)} $ sortie`);option.value=model.id;$('openai-model').append(option);}const other=el('option','Autre modèle · saisir son identifiant');other.value='custom';$('openai-model').append(other);if(modelCatalog.some(m=>m.id===remembered))$('openai-model').value=remembered;else{$('openai-model').value='custom';$('custom-model').value=remembered;}modelChanged();}catch(e){$('model-cost').textContent='Liste indisponible. Relance l’application pour charger le choix des modèles.';}}
$('openai-model').onchange=modelChanged;$('custom-model').oninput=modelChanged;loadModels();
